### ISSUE TITLE
Can't connect to kemono.party, but can connect to kemono.su

### ISSUE THREAD

**Issue by AndreyVSolovyov** [darkdragn/party#16]
Hi. I can't connect to kemono.party from my location, server break the connection, but i can connect to kemono.su. How can I download from the kemono .su instead of party?

**Comment by julesupss** [comment]
I've added support to change it by doing 'party kemono --site https://kemono.su {service} {user}' in #21 as well. Justing wait for it to be pulled to main.

**Comment by darkdragn** [comment]
I merged @julesupss items. It's up and running on v0.6.1
