### ISSUE TITLE
ignore_extenstions usage

### ISSUE THREAD

**Issue by ComradeCakey** [darkdragn/party#3]
how do i use this?
can you show me an example using this user:
https://kemono.party/fanbox/user/3316400

**Comment by darkdragn** [comment]
A quick example would be ignoring all .psd files and all .zip files: `party kemono patreon 2613194 -i psd -i zip`

the `-i` flag can be used multiple times and will not only ignore the extensions but also add them to the .info the that download folder allowing you to have those extensions ignored for future `update` runs of the command.
