### ISSUE TITLE
Not a issue but a basic gui

### ISSUE THREAD

**Issue by lolbroek-droid** [darkdragn/party#32]
Hi,

i Have made a basic gui for Party.
it still requires party to be installed along with PySimpleGui, it doesn't have full functionality for kemono yet but it works fine for coomer.

just if you want to i can send you it.

the only i ask is if you will use it for the publick party i want to have credits on like the github page.

Bye :3

**Comment by lolbroek-droid** [comment]
here is a image of how it looks.
![Screenshot from 2024-02-03 23-43-18](https://github.com/darkdragn/party/assets/77837807/f0233b85-04f9-4f3c-8491-031eab7d816e)

**Comment by darkdragn** [comment]
Sorry, man. I've been distracted by family things for a while. I'd love to see it if you want to attach it to this thread! 

Honestly, I'm just happy to see people motivated to write code for fun!

**Comment by lolbroek-droid** [comment]
alr i'll attatch it.
sadly enough pysimplegui now needs a license but the license is free if you sign up for the personal plan. no creddit card or anything required

```
#!/usr/bin/env python3 ./partygui.py

import PySimpleGUI as sg
import time
import os

platform = ""
website = ""
creator = ""

sg.theme("LightBlue2")

layout = [[sg.Text("What Platform?"), sg.Radio("Coomer", "coom_or_kemono", key="-COOMER-"), sg.Radio("Kemono", "coom_or_kemono", key="-KEMONO-")],
          [sg.Text("(Only If Coomer) What Platform?"), sg.Radio("Onlyfans", "of_or_fa", key="-ONLYFANS-"), sg.Radio("Fansly", "of_or_fa", key="-FANSLY-")],
          [sg.Text("What Is The Username/id?"), sg.Input(key="-USERNAME-", do_not_clear=True, size=(25, 1))],
          [sg.Submit("Start Download"), sg.Cancel()]
]

window = sg.Window('Party GUI', layout)


event, values = window.read()

window.close()

creator = values['-USERNAME-']

if values['-COOMER-']:
    platform = "coomer"
else:
    platform = "kemono"

if values['-ONLYFANS-']:
    website = "onlyfans"
else:
    website = "fansly"

if platform == "kemono":
    os.system("party kemono patreon " + (creator))
else:
    os.system("party coomer %s %s" % (website, creator))

```

it is just a quick thing developed by me on ubuntu
